package com.desh2403.bento_ds_compose.uikit.theme

import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color

data class PAButtonPalette(
    val enabledBg: Color,
    val enabledFg: Color,
    val hoverBg: Color,
    val hoverFg: Color,
    val focusBg: Color,
    val focusFg: Color,
    val disabledBg: Color,
    val disabledFg: Color,
)

data class BentoDSButtonColors(
    val primarySolidButton: PAButtonPalette,
    val primaryOutlinedButton: PAButtonPalette,
    val primaryTransparentButton: PAButtonPalette,

    val secondarySolidButton: PAButtonPalette,
    val secondaryOutlinedButton: PAButtonPalette,
    val secondaryTransparentButton: PAButtonPalette,

    val dangerSolidButton: PAButtonPalette,
    val dangerOutlinedButton: PAButtonPalette,
    val dangerTransparentButton: PAButtonPalette,

    val positiveSolidButton: PAButtonPalette,
    val positiveOutlinedButton: PAButtonPalette,
    val positiveTransparentButton: PAButtonPalette,

    val warningSolidButton: PAButtonPalette,
    val warningOutlinedButton: PAButtonPalette,
    val warningTransparentButton: PAButtonPalette,
)

@Composable
fun paButtonColors() =
    BentoDSButtonColors(
        primarySolidButton = PAButtonPalette(
            enabledBg = BentoDSTheme.colors.primary.solidEnabledBg,
            enabledFg = BentoDSTheme.colors.primary.solidEnabledFg,
            hoverBg = BentoDSTheme.colors.primary.solidHoverBg,
            hoverFg = BentoDSTheme.colors.primary.solidHoverFg,
            focusBg = BentoDSTheme.colors.primary.solidFocusBg,
            focusFg = BentoDSTheme.colors.primary.solidFocusFg,
            disabledBg = BentoDSTheme.colors.disabled.solidBg,
            disabledFg = BentoDSTheme.colors.disabled.solidFg,
        ),
        primaryOutlinedButton = PAButtonPalette(
            enabledBg = BentoDSTheme.colors.primary.transparentEnabledBg,
            enabledFg = BentoDSTheme.colors.primary.outlineEnabled,
            hoverBg = BentoDSTheme.colors.primary.transparentHoverBg,
            hoverFg = BentoDSTheme.colors.primary.outlineHover,
            focusBg = BentoDSTheme.colors.primary.transparentFocusBg,
            focusFg = BentoDSTheme.colors.primary.outlineFocus,
            disabledBg = BentoDSTheme.colors.disabled.transparentBg,
            disabledFg = BentoDSTheme.colors.disabled.outline,
        ),
        primaryTransparentButton = PAButtonPalette(
            enabledBg = BentoDSTheme.colors.primary.transparentEnabledBg,
            enabledFg = BentoDSTheme.colors.primary.transparentEnabledFg,
            hoverBg = BentoDSTheme.colors.primary.transparentHoverBg,
            hoverFg = BentoDSTheme.colors.primary.transparentHoverFg,
            focusBg = BentoDSTheme.colors.primary.transparentFocusBg,
            focusFg = BentoDSTheme.colors.primary.transparentFocusFg,
            disabledBg = BentoDSTheme.colors.disabled.transparentBg,
            disabledFg = BentoDSTheme.colors.disabled.transparentFg,
        ),

        secondaryOutlinedButton = PAButtonPalette(
            enabledBg = BentoDSTheme.colors.secondary.transparentEnabledBg,
            enabledFg = BentoDSTheme.colors.secondary.outlineEnabled,
            hoverBg = BentoDSTheme.colors.secondary.transparentHoverBg,
            hoverFg = BentoDSTheme.colors.secondary.outlineHover,
            focusBg = BentoDSTheme.colors.secondary.transparentFocusBg,
            focusFg = BentoDSTheme.colors.secondary.outlineFocus,
            disabledBg = BentoDSTheme.colors.disabled.transparentBg,
            disabledFg = BentoDSTheme.colors.disabled.outline,
        ),
        secondarySolidButton = PAButtonPalette(
            enabledBg = BentoDSTheme.colors.secondary.solidEnabledBg,
            enabledFg = BentoDSTheme.colors.secondary.solidEnabledFg,
            hoverBg = BentoDSTheme.colors.secondary.solidHoverBg,
            hoverFg = BentoDSTheme.colors.secondary.solidHoverFg,
            focusBg = BentoDSTheme.colors.secondary.solidFocusBg,
            focusFg = BentoDSTheme.colors.secondary.solidFocusFg,
            disabledBg = BentoDSTheme.colors.disabled.solidBg,
            disabledFg = BentoDSTheme.colors.disabled.solidFg,
        ),
        secondaryTransparentButton = PAButtonPalette(
            enabledBg = BentoDSTheme.colors.secondary.transparentEnabledBg,
            enabledFg = BentoDSTheme.colors.secondary.transparentEnabledFg,
            hoverBg = BentoDSTheme.colors.secondary.transparentHoverBg,
            hoverFg = BentoDSTheme.colors.secondary.transparentHoverFg,
            focusBg = BentoDSTheme.colors.secondary.transparentFocusBg,
            focusFg = BentoDSTheme.colors.secondary.transparentFocusFg,
            disabledBg = BentoDSTheme.colors.disabled.transparentBg,
            disabledFg = BentoDSTheme.colors.disabled.transparentFg,
        ),

        dangerOutlinedButton = PAButtonPalette(
            enabledBg = BentoDSTheme.colors.danger.transparentEnabledBg,
            enabledFg = BentoDSTheme.colors.danger.outlineEnabled,
            hoverBg = BentoDSTheme.colors.danger.transparentHoverBg,
            hoverFg = BentoDSTheme.colors.danger.outlineHover,
            focusBg = BentoDSTheme.colors.danger.transparentFocusBg,
            focusFg = BentoDSTheme.colors.danger.outlineFocus,
            disabledBg = BentoDSTheme.colors.disabled.transparentBg,
            disabledFg = BentoDSTheme.colors.disabled.outline,
        ),
        dangerSolidButton = PAButtonPalette(
            enabledBg = BentoDSTheme.colors.danger.solidEnabledBg,
            enabledFg = BentoDSTheme.colors.danger.solidEnabledFg,
            hoverBg = BentoDSTheme.colors.danger.solidHoverBg,
            hoverFg = BentoDSTheme.colors.danger.solidHoverFg,
            focusBg = BentoDSTheme.colors.danger.solidFocusBg,
            focusFg = BentoDSTheme.colors.danger.solidFocusFg,
            disabledBg = BentoDSTheme.colors.disabled.solidBg,
            disabledFg = BentoDSTheme.colors.disabled.solidFg,
        ),
        dangerTransparentButton = PAButtonPalette(
            enabledBg = BentoDSTheme.colors.danger.transparentEnabledBg,
            enabledFg = BentoDSTheme.colors.danger.transparentEnabledFg,
            hoverBg = BentoDSTheme.colors.danger.transparentHoverBg,
            hoverFg = BentoDSTheme.colors.danger.transparentHoverFg,
            focusBg = BentoDSTheme.colors.danger.transparentFocusBg,
            focusFg = BentoDSTheme.colors.danger.transparentFocusFg,
            disabledBg = BentoDSTheme.colors.disabled.transparentBg,
            disabledFg = BentoDSTheme.colors.disabled.transparentFg,
        ),

        warningSolidButton = PAButtonPalette(
            enabledBg = BentoDSTheme.colors.warning.solidEnabledBg,
            enabledFg = BentoDSTheme.colors.warning.solidEnabledFg,
            hoverBg = BentoDSTheme.colors.warning.solidHoverBg,
            hoverFg = BentoDSTheme.colors.warning.solidHoverFg,
            focusBg = BentoDSTheme.colors.warning.solidFocusBg,
            focusFg = BentoDSTheme.colors.warning.solidFocusFg,
            disabledBg = BentoDSTheme.colors.disabled.solidBg,
            disabledFg = BentoDSTheme.colors.disabled.solidFg,
        ),
        warningOutlinedButton = PAButtonPalette(
            enabledBg = BentoDSTheme.colors.warning.transparentEnabledBg,
            enabledFg = BentoDSTheme.colors.warning.outlineEnabled,
            hoverBg = BentoDSTheme.colors.warning.transparentHoverBg,
            hoverFg = BentoDSTheme.colors.warning.outlineHover,
            focusBg = BentoDSTheme.colors.warning.transparentFocusBg,
            focusFg = BentoDSTheme.colors.warning.outlineFocus,
            disabledBg = BentoDSTheme.colors.disabled.transparentBg,
            disabledFg = BentoDSTheme.colors.disabled.outline,
        ),
        warningTransparentButton = PAButtonPalette(
            enabledBg = BentoDSTheme.colors.warning.transparentEnabledBg,
            enabledFg = BentoDSTheme.colors.warning.transparentEnabledFg,
            hoverBg = BentoDSTheme.colors.warning.transparentHoverBg,
            hoverFg = BentoDSTheme.colors.warning.transparentHoverFg,
            focusBg = BentoDSTheme.colors.warning.transparentFocusBg,
            focusFg = BentoDSTheme.colors.warning.transparentFocusFg,
            disabledBg = BentoDSTheme.colors.disabled.transparentBg,
            disabledFg = BentoDSTheme.colors.disabled.transparentFg,
        ),

        positiveSolidButton = PAButtonPalette(
            enabledBg = BentoDSTheme.colors.positive.solidEnabledBg,
            enabledFg = BentoDSTheme.colors.positive.solidEnabledFg,
            hoverBg = BentoDSTheme.colors.positive.solidHoverBg,
            hoverFg = BentoDSTheme.colors.positive.solidHoverFg,
            focusBg = BentoDSTheme.colors.positive.solidFocusBg,
            focusFg = BentoDSTheme.colors.positive.solidFocusFg,
            disabledBg = BentoDSTheme.colors.disabled.solidBg,
            disabledFg = BentoDSTheme.colors.disabled.solidFg,
        ),
        positiveOutlinedButton = PAButtonPalette(
            enabledBg = BentoDSTheme.colors.positive.transparentEnabledBg,
            enabledFg = BentoDSTheme.colors.positive.outlineEnabled,
            hoverBg = BentoDSTheme.colors.positive.transparentHoverBg,
            hoverFg = BentoDSTheme.colors.positive.outlineHover,
            focusBg = BentoDSTheme.colors.positive.transparentFocusBg,
            focusFg = BentoDSTheme.colors.positive.outlineFocus,
            disabledBg = BentoDSTheme.colors.disabled.transparentBg,
            disabledFg = BentoDSTheme.colors.disabled.outline,
        ),
        positiveTransparentButton = PAButtonPalette(
            enabledBg = BentoDSTheme.colors.positive.transparentEnabledBg,
            enabledFg = BentoDSTheme.colors.positive.transparentEnabledFg,
            hoverBg = BentoDSTheme.colors.positive.transparentHoverBg,
            hoverFg = BentoDSTheme.colors.positive.transparentHoverFg,
            focusBg = BentoDSTheme.colors.positive.transparentFocusBg,
            focusFg = BentoDSTheme.colors.positive.transparentFocusFg,
            disabledBg = BentoDSTheme.colors.disabled.transparentBg,
            disabledFg = BentoDSTheme.colors.disabled.transparentFg,
        ),
    )